### ISSUE TITLE
[Technical Question] DeviceStreamRequest and other device stream functionality not present in 1.28.1?

### ISSUE THREAD

**Issue by emilm** [Azure/azure-iot-sdk-csharp#1695]
Hello, I wonder what happened to all the Device Stream functionality in later releases. Am I doomed to run 1.27.1-preview-003 forever to have this functionality?

Things like DeviceStreamRequest, DeviceStreamResponse, CreateStreamAsync() on ServiceClient etc

Thanks!

**Comment by drwill-ms** [comment]
Hi @emilm - the REST API that supports device streaming is still in preview in the Azure IoT Hub service, so the corresponding support in the SDK is not yet in a general audience (GA) version of the SDK. We'll see if we can get a IoT Hub program manager to reach out to you to learn more about your scenario and needs, okay?

**Comment by emilm** [comment]
> Hi @emilm - the REST API that supports device streaming is still in preview in the Azure IoT Hub service, so the corresponding support in the SDK is not yet in a general audience (GA) version of the SDK. We'll see if we can get a IoT Hub program manager to reach out to you to learn more about your scenario and needs, okay?

Thanks! it is very useful for access to devices in production via SSH or other means as a backup. It has been working since I started trying it, I wonder if it's going to be removed in the future or if it's a sure thing and will have future support.

**Comment by kiranpradeep** [comment]
The preview versions (1.29.0-preview-*) works with netcoreapp3.1. But for net5.0, the preview versions start failing/exceptions (System.NotSupportedException). It does not give a good impression on future support of the feature.

**Comment by vinagesh** [comment]
Sorry about the inconvenience. There seems to be an issue with 1.29.0-preview-*. However, if you upgrade to 1.32.0-preivew-*, it should work with net5.0 as well. Let me know if that does not work for you.

**Comment by ash2017** [comment]
This feature is very high priority for us and many customers have asked for this capability in GA. We will definitely be releasing GA with higher limits for number of streams and data/day allowed. We are still in planning phase, so don't have concrete timelines but this feature will definitely GA.

**Comment by vinagesh** [comment]
@emilm - Let me know if you have further questions and is it fine to close the issue now?

**Comment by kiranpradeep** [comment]
@vinagesh With 1.32.0-preview-\*, usage of DeviceStreamRequest is giving compilation error as below. No such error with 1.29.0-preview-* though.

> error CS0246: The type or namespace name 'DeviceStreamRequest' could not be found (are you missing a using directive or an assembly reference?

**Comment by vinagesh** [comment]
Did you install the preview 1.32.0-preview-001? Can you clean build and test? I don't see any compilation issues on my end. However, there has been one change where we renamed a property from 'streamRequest.**Url**' to 'streamRequest.**Uri**'.

**Comment by vinagesh** [comment]
![Uploading image.png…]()

**Comment by kiranpradeep** [comment]
Thanks. Surprisingly 1.32.0-preview-001 worked. But not 1.32.0-preview-*

**Comment by vinagesh** [comment]
Sounds good. Does this resolve all the issues?

**Comment by kiranpradeep** [comment]
I am unrelated to OP. Nothing pending from my side. Thanks again.

**Comment by az-iot-builder-01** [comment]
@emilm, @kiranpradeep, @vinagesh, @ash2017, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
